require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "vue",
    "git_rebase",
    "go",
    "html",
    "javascript",
    "json",
    "lua",
    "markdown",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "toml",
    "typescript",
    "vimdoc",
    "yaml",
  },
  sync_install = true,
  auto_install = true,
  ignire_install = {},
})
